# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- security-checks
sast:
  stage: security-checks
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
variables:
  SECRET_DETECTION_ENABLED: 'true'
secret_detection:
  stage: security-checks

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y libgl1-mesa-dev
  script:
    - make build-test-glsl
    - make build-test-tasks
    - make build-ray
    - make build-con
  artifacts:
    paths:
      - bin-test
      - bin
test:
  stage: test
  script:
    - ./bin-test/test-glsl
    - ./bin-test/test-tasks